FROM asia.gcr.io/gdp-labs/gl-base/debian:stable-slim

ENV TZ=Asia/Jakarta

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY target/x86_64-unknown-linux-musl/release/vsock-server ./

COPY kmstool_enclave_cli ./

COPY libnsm.so ./

ENV LD_LIBRARY_PATH ":/libnsm.so"

CMD ["./vsock-server", "--port", "5005"]

