[package]
name = "vsock-server"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.2"
log = "0.4"
nix = "0.20"
byteorder = "1.3"
base64 = "0.21.7"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
types = { path = "../types" }